# Generated by Django 5.2.1 on 2025-05-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Alimentación', 'Alimentación'), ('Transporte', 'Transporte'), ('Entretenimiento', 'Entretenimiento'), ('Salud', 'Salud'), ('Otros', 'Otros')], default='Otros', max_length=50),
        ),
    ]
